### ISSUE TITLE
Problem with multibytes chars on version 1.0.0

### ISSUE THREAD

**Issue by nalmar** [lolli42/FineDiff#17]
Hi,
There something wrong with opcode start and end when there is a multibyte character in the strings.

( strikethrough for \<DEL> and bold for \<INS> )
Test 0 multibytes : Hello world -> Hello world2
Result : Hello ~~world~~**world2**

Test 1 multibytes : Héllo world -> Héllo world2
Result : Héllo w~~orld~~**orld2**

Test 2 multibytes : Héllò world -> Héllò world2
Result : Héllò wo~~rld~~**rld2**

I'm comparing strings with the word granularity, on php 7.2.21 with FineDiff 1.0.0.
This problem isn't there with FineDiff 0.3.1, without the use of mb_* variants of strlen and substr.

**Comment by nalmar** [comment]
> Hi, There something wrong with opcode start and end when there is a multibyte character in the strings.
> 
> ( strikethrough for <DEL> and bold for <INS> ) Test 0 multibytes : Hello world -> Hello world2 Result : Hello ~world~**world2**
> 
> Test 1 multibytes : Héllo world -> Héllo world2 Result : Héllo w~orld~**orld2**
> 
> Test 2 multibytes : Héllò world -> Héllò world2 Result : Héllò wo~rld~**rld2**
> 
> I'm comparing strings with the word granularity, on php 7.2.21 with FineDiff 1.0.0. This problem isn't there with FineDiff 0.3.1, without the use of mb_* variants of strlen and substr.

**Comment by lolli42** [comment]
Confirmed. Added to tests picking up your examples. Will have a look if we can resolve this.

**Comment by lolli42** [comment]
Reason is method 'extractFragments()' which works with strspn() / strcspn() - those functions are not multibyte safe, work on a byte level and then count wrongly. I'll re-implement the method.

**Comment by nalmar** [comment]
And thanks you for the fix.
