### ISSUE TITLE
Comparing from a word without newline to text with a newline considers the entire text as one word

### ISSUE THREAD

**Issue by dveldmeijer** [lolli42/FineDiff#28]
In the example below I would not expect the complete "hallo123" word to be strikethrough'ed when comparing it to a text that is preceded with a newline. Maybe it should only show the string on the second line as new, or add a tiny green character at the end of the first word to indicate a newline was added. What do you think?

```php
$diff = new Diff(new Word());
echo $diff->render("hallo123", "hallo123\nhallo12345");
```

```
object(cogpowered\FineDiff\Parser\Opcodes)#3250 (1) {
  ["opcodes":protected]=>
  array(1) {
    [0]=>
    string(25) "d8i19:hallo123
hallo12345"
  }
}
``` 
![Screenshot 2023-08-24 130004](https://github.com/lolli42/FineDiff/assets/6987134/585e3d6c-0fa8-4c94-9160-036601943aa6)

**Comment by lolli42** [comment]
Hey.

I added a couple of tests with https://github.com/lolli42/FineDiff/pull/31 to check current behavior.

I tend to agree, it would be better if the diff would end up with this, with doing "Word" level diffing.
```
'Hello<ins>' . chr(10) . 'World</ins>'
```

Changing this requires a deeper dive into the parser internals, which I currently can't provide. Would you have some time to take a look and see if it could be changed somehow?

However, according to the tests, the above is exactly what "Character" level diffing produces, which is the default when you don't provide a granularity to Diff. Maybe this is sufficient to solve your problem?

**Comment by lolli42** [comment]
Hey.

I hope it's ok to close here for now: The issue can be worked around using a different 'granularity' and there was no further feedback. Feel free to re-open this if you think a change would be feasible.

**Comment by dveldmeijer** [comment]
@lolli42 Hi! Sorry, I did not have time yet to dig into the parser diff function. I noticed that the character diff does split on the newline character but I want to use word diff. I will create a PR and/or reopen this issue once I've had time to look at it!

**Comment by lolli42** [comment]
Sounds good. Thank you!
